config/urls.py
# -*- coding: utf-8 -*-
from rest_framework import schemas

from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views

from instanotifier.feedsource import urls as feedsource_urls


schema_view = schemas.get_schema_view(title="InstaNotifier stored notifications API", description="InstaNotifier stored notifications API")

urlpatterns = [
    url(r'^', include(feedsource_urls)),
    url(r'^feeds/', include(feedsource_urls)),
    url(r'^home/$', TemplateView.as_view(template_name='pages/home.html'), name='home'),

    # Django Admin, use {% url 'admin:index' %}
    url(settings.ADMIN_URL, admin.site.urls),

    # User management
    url(r'^users/', include('instanotifier.users.urls', namespace='users')),
    url(r'^accounts/', include('allauth.urls')),

    # API.v1
    url(r'^api-schema/', schema_view),
    url(r'^api/v1/', include('instanotifier.api.urls', namespace='api-v1')),

    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r'^400/$', default_views.bad_request, kwargs={'exception': Exception('Bad Request!')}),
        url(r'^403/$', default_views.permission_denied, kwargs={'exception': Exception('Permission Denied')}),
        url(r'^404/$', default_views.page_not_found, kwargs={'exception': Exception('Page not Found')}),
        url(r'^500/$', default_views.server_error),
    ]
    if 'debug_toolbar' in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns += [
            url(r'^__debug__/', include(debug_toolbar.urls)),
        ]

instanotifier/api/urls.py
from django.conf.urls import url, include
from rest_framework.routers import DefaultRouter

from instanotifier.api.notification import views as notification_views

app_name = "api-v1"

router = DefaultRouter()
router.include_root_view = False

router.register(
    r'rss-search',
    notification_views.NotificationSearchViewSet,
    basename='rss'
)

urlpatterns = router.urls

urlpatterns += [
    url(
        r"^$",
        notification_views.NotificationListView.as_view(),
        name="rssnotification-list",
    ),
    # url(r'^notifications/(?P<pk>\d+)/rating/(?P<rating>[\w]+)$', notification_views.NotificationVotingView.as_view(), name='rssnotification-rating'),
    url(
        r"^notifications/rating/$",
        notification_views.NotificationVotingView.as_view(),
        name="rssnotification-rating",
    ),
    url(
        r"^dates/$",
        notification_views.NotificationDatesListView.as_view(),
        name="rssnotification-date-list",
    ),
]

instanotifier/feedsource/urls.py
from django.conf.urls import url

from instanotifier.feedsource import views

app_name = "feedsource"

urlpatterns = [
    url(regex=r"^$", view=views.FeedSourceListView.as_view(), name="list"),
    url(
        regex=r"^update/(?P<pk>\d+)/$",
        view=views.FeedSourceUpdateView.as_view(),
        name="update",
    ),
    url(regex=r"^create/$", view=views.FeedSourceCreateView.as_view(), name="create"),
]

instanotifier/users/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url

from . import views


app_name = "users"
urlpatterns = [
    url(regex=r"^$", view=views.UserListView.as_view(), name="list"),
    url(regex=r"^~redirect/$", view=views.UserRedirectView.as_view(), name="redirect"),
    url(
        regex=r"^(?P<username>[\w.@+-]+)/$",
        view=views.UserDetailView.as_view(),
        name="detail",
    ),
    url(regex=r"^~update/$", view=views.UserUpdateView.as_view(), name="update"),
]

instanotifier/feedsource/models.py
from django.db import models


class FeedSourceQuerySet(models.QuerySet):
    def enabled(self):
        return self.filter(enabled=True)


class FeedSource(models.Model):
    name = models.CharField(max_length=64)
    url = models.URLField(max_length=2083)
    email_to = models.CharField(max_length=255)
    enabled = models.BooleanField(default=True)

    notes = models.TextField(blank=True, null=True)

    created_on = models.DateTimeField(auto_now_add=True)
    last_modified = models.DateTimeField(auto_now=True)

    objects = FeedSourceQuerySet.as_manager()

    def __str__(self):
        return f"{self.name} - {self.email_to[:40]}"

instanotifier/users/models.py
# -*- coding: utf-8 -*-
from django.contrib.auth.models import AbstractUser
from django.urls import reverse
from django.db import models
from django.utils.translation import ugettext_lazy as _


class User(AbstractUser):

    # First Name and Last Name do not cover name patterns
    # around the globe.
    name = models.CharField(_("Name of User"), blank=True, max_length=255)

    def __str__(self):
        return self.username

    def get_absolute_url(self):
        return reverse("users:detail", kwargs={"username": self.username})

instanotifier/feedsource/forms.py
from instanotifier.feedsource.models import FeedSource
from django import forms


class FeedSourceForm(forms.ModelForm):
    class Meta:
        model = FeedSource
        fields = "__all__"

instanotifier/notification/forms.py
import hashlib

from django import forms
from instanotifier.notification.models import RssNotification


class RssNotificationForm(forms.ModelForm):
    class Meta:
        model = RssNotification
        fields = ["entry_id", "title", "summary", "link", "published_parsed"]

    def __init__(self, *args, **kwargs):
        super(RssNotificationForm, self).__init__(*args, **kwargs)
        if self.data and self.data.get("id", None):
            self.data.update(entry_id=self.data["id"])

instanotifier/api/notification/views.py
from django_filters.rest_framework import DjangoFilterBackend

from rest_framework.generics import ListAPIView, GenericAPIView, get_object_or_404
from rest_framework.renderers import (
    BrowsableAPIRenderer,
    JSONRenderer,
)

from rest_framework.pagination import PageNumberPagination
from rest_framework import filters
from rest_framework import status

from rest_framework.response import Response
from rest_framework.exceptions import ValidationError

from django_elasticsearch_dsl_drf.viewsets import DocumentViewSet
from django_elasticsearch_dsl_drf.filter_backends import MultiMatchSearchFilterBackend

from django.utils.functional import cached_property

from instanotifier.api.notification.renderers import ListViewTemplateRenderer, TemplateHTMLRendererBase
from instanotifier.api.serializers import (
    RssNotificationSerializer,
    RssNotificationDateSerializer,
)
from instanotifier.api.notification.rating import RatingManager
from instanotifier.notification.models import RssNotification, Ratings

from instanotifier.notification.documents import RssNotificationDocument


class PaginationSettings(PageNumberPagination):
    page_size = 50


class CustomMultiMatchSearchFilterBackend(MultiMatchSearchFilterBackend):
    search_param = "search"

    def should_search(self, request):
        search_terms = self.get_search_query_params(request)
        return bool(search_terms)


class NotificationSearchViewSet(DocumentViewSet):
    """ Endpoint to be used for searching through ElasticSearch """

    document = RssNotificationDocument
    queryset = RssNotification.objects.all()

    renderer_classes = (JSONRenderer,)

    filter_backends = (CustomMultiMatchSearchFilterBackend,)
    multi_match_search_fields = ["title", "summary"]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # override the search object with the django_elasticsearch_dsl implementation in order to provide
        # the Search.to_queryset() method
        self.search = self.document.search(using=self.client, index=self.index)

    def _should_search(self):
        do_search = False
        for es_filter_backend in list(self.filter_backends):
            if es_filter_backend().should_search(self.request):
                do_search = True
        return do_search

    def filter_queryset(self, queryset):
        """
        :param queryset: of type django_elasticsearch_dsl.search.Search
        :return: django_elasticsearch_dsl.search.Search object
        """
        es_query = super().filter_queryset(queryset)
        es_query = es_query.extra(from_=0, size=500).sort("-published_parsed", "_score")
        queryset = es_query

        return queryset

    def list(self, request, *args, **kwargs):
        """
        Shows the ES raw search result
        """
        queryset = self.filter_queryset(self.get_queryset())
        data = queryset.execute()
        return Response(data.to_dict())


class NotificationListView(ListAPIView):
    """ Renders list of RssNotification objects. Searching through the ElasticSearch """

    queryset = RssNotification.objects.all()

    serializer_class = RssNotificationSerializer
    renderer_classes = (ListViewTemplateRenderer, JSONRenderer, BrowsableAPIRenderer)
    pagination_class = PaginationSettings

    filter_backends = (DjangoFilterBackend,)
    filter_fields = {
        "published_parsed": [
            "date"
        ],  # filtering datetime using the __date lookup function
        "rating": ["exact"],
    }

    @cached_property
    def rating_manager(self):
        return RatingManager()

    def _filter_by_elasticsearch(self, queryset):
        """
        Return search results from ElasticSearch if the search params were specified
        :param queryset:
        :return: QuerySet
        """
        search_view = NotificationSearchViewSet()
        search_view.setup(self.request, *self.args, **self.kwargs)
        if search_view._should_search():
            es_query = search_view.filter_queryset(search_view.get_queryset())
            queryset = es_query.to_queryset()

        return queryset

    def filter_queryset(self, queryset):
        queryset = self._filter_by_elasticsearch(queryset)
        queryset = super().filter_queryset(queryset)

        # custom logic for excluding of downvoted RssNotifications.
        queryset = self.rating_manager.filter_queryset(self.request, queryset, self)

        if "published_parsed__date" in self.request.query_params:
            # save current date filtered to highlight it on the page
            self.filter_date_used = self.request.query_params["published_parsed__date"]

        return queryset


class NotificationDatesListView(ListAPIView):
    """ Renders list of dates picked from the RssNotification published_parsed field. """

    template_name = "api/notification/rssnotification_date_list.html"
    renderer_classes = (TemplateHTMLRendererBase, JSONRenderer)
    serializer_class = RssNotificationDateSerializer

    def get_queryset(self):
        """
        Returns the queryset containing entries having the date and rating stats fields.
        """
        date_times = RssNotification.objects.get_dates_stats()
        return date_times


class NotificationVotingView(GenericAPIView):
    """Endpoint for setting of Notification rating. """

    # TODO: allow for current user entries only
    queryset = RssNotification.objects.all()
    serializer_class = RssNotificationSerializer

    def get_object(self):
        pk = self.request.data.get("id")
        queryset = self.filter_queryset(self.get_queryset())
        obj = get_object_or_404(queryset, pk=pk)
        # May raise a permission denied
        self.check_object_permissions(self.request, obj)

        return obj

    def _get_rating_value(self):
        """ Get the rating value from the request. """

        rating = self.request.data.get("rating", None)
        if rating is None:
            raise ValidationError("The 'rating' parameter was not specified.")

        rating_value = Ratings.get_value_or_none(rating)
        if rating_value is None:
            raise ValidationError("The 'rating' parameter was incorrectly specified.")

        return rating_value

    def patch(self, request, *args, **kwargs):
        instance = self.get_object()

        rating_data = {"rating": self._get_rating_value()}

        serializer = self.get_serializer(instance, data=rating_data, partial=True)
        if serializer.is_valid(raise_exception=True):
            serializer.save()
        else:
            return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

        if getattr(instance, "_prefetched_objects_cache", None):
            # If 'prefetch_related' has been applied to a queryset, we need to
            # forcibly invalidate the prefetch cache on the instance.
            instance._prefetched_objects_cache = {}

        return Response(serializer.data)

instanotifier/feedsource/views.py
from django.shortcuts import render, reverse

from django.views.generic.edit import CreateView, UpdateView
from django.views.generic.list import ListView

from instanotifier.feedsource.models import FeedSource
from instanotifier.feedsource.forms import FeedSourceForm


class FeedSourceListView(ListView):
    model = FeedSource
    template_name = "feedsource/feedsource_list.html"


class FeedSourceCreateUpdateMixin(object):
    model = FeedSource
    form_class = FeedSourceForm
    context_object_name = "feedsource"

    def get_success_url(self):
        return reverse("feedsource:list")


class FeedSourceCreateView(FeedSourceCreateUpdateMixin, CreateView):
    template_name = "feedsource/feedsource_create.html"


class FeedSourceUpdateView(FeedSourceCreateUpdateMixin, UpdateView):
    template_name = "feedsource/feedsource_update.html"

instanotifier/notification/views.py
import logging
from datetime import timedelta

from django.utils import timezone
from django.db.utils import IntegrityError

from instanotifier.notification.forms import RssNotificationForm
from instanotifier.notification.models import RssNotification

logger = logging.getLogger('general_file')


def create_rssnotification_instances(feed_items, feed_source=None):
    saved_pks = list()
    for item in feed_items:
        form = RssNotificationForm(data=item)
        if form.is_valid():
            cd = form.cleaned_data
            entry_id = cd["entry_id"]
            title = cd["title"]

            if RssNotification.objects.filter(
                title=title, created_on__gte=timezone.now() - timedelta(days=1)
            ).exists():
                logger.info(f"Skipping item `{title}` as already existing.")
                continue

            try:
                instance = form.save()
            except IntegrityError:
                logger.info(f"Skipping item `{title}` as already existing.")
                continue

            if feed_source:
                instance.feed_source = feed_source
                instance.save()

            saved_pks.append(instance.pk)

    return saved_pks

instanotifier/users/views.py
# -*- coding: utf-8 -*-
from django.urls import reverse
from django.views.generic import DetailView, ListView, RedirectView, UpdateView

from django.contrib.auth.mixins import LoginRequiredMixin

from .models import User


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = "username"
    slug_url_kwarg = "username"


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})


class UserUpdateView(LoginRequiredMixin, UpdateView):

    fields = ["name"]

    # we already imported User in the view code above, remember?
    model = User

    # send the user back to their own page after a successful update
    def get_success_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})

    def get_object(self):
        # Only get the User record for the user making the request
        return User.objects.get(username=self.request.user.username)


class UserListView(LoginRequiredMixin, ListView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = "username"
    slug_url_kwarg = "username"

instanotifier/templates/api/notification/rssnotification_api_list.html
{% extends "base.html" %}

{% load staticfiles %}
{% load bootstrap_pagination %}

{% block css %}
  {{ block.super }}
  <link href="{% static 'css/notification-list.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
  <span id="date-list-url" data-url="{% url 'api-v1:rssnotification-date-list'%}"></span>
  <span id="date-list-filtering-url" data-url="{% url 'api-v1:rssnotification-list' %}" data-filter-param="?published_parsed__date="></span>
  <span id="filter_date_used" data-date="{{ filter_date_used }}"></span>
  <span id="rating-url" data-url="{% url 'api-v1:rssnotification-rating' %}"></span>

  <div class="row notification-list-page-header">
    <div class="col-md-5">
      {% if paginator %}
      {% bootstrap_paginate paginator.page range=10 %}
      {% endif %}
    </div>
    <div class="col-md-3">
      <form method="get">
        <div class="controls "><input type="text" name="search" class="form-control"></div>
        <!--<input type="submit" name="" value="Submit" class="btn btn-primary btn-default" id="submit-id-">-->
      </form>
    </div>
    <div class="col-md-3">
      {% if rating_checkbox.is_shown %}
      <div class="checkbox" style="">
        <a href="{{ rating_checkbox.url }}">
          <label><input type="checkbox" value="" {{ rating_checkbox_is_checked }}
                        onclick='window.location.assign("{{ rating_checkbox.url }}")'>Exclude downvoted items from listing</label>
        </a>
      </div>
      {% endif %}
    </div>
    <div class="col-md-1">
      {% if filter_form %}
      <button style="float: right; " data-toggle="modal" data-target="#filtersModal"
              class="btn btn-default">
        <span class="glyphicon glyphicon-wrench" aria-hidden="true"></span>
        Search
      </button>
    </div>
    {% endif %}
  </div>

  <div class="row">
    <div class="col-md-9 notification-list">
      <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
        {% for notification in results %}
          <div class="panel panel-default notification-list-item" data-id="{{ notification.id }}" data-rating="{{ notification.rating }}">
            <div class="panel-heading" role="tab" id="notification-heading-{{ forloop.counter }}">
              <h4 class="panel-title">
                <div class="row">
                  <div class="col-md-10">
                    <a role="button" data-toggle="collapse" data-parent="#accordion" href="#notification-data-{{ forloop.counter }}" aria-expanded="false" aria-controls="notification-data-{{ forloop.counter }}">
                      {{ notification.title }}
                      <span class="label label-info">{{ notification.country }}</span>
                      </p>
                      <span>{{ notification.published_parsed }}</span>
                      <span class="label label-default">{{ notification.source_name }}</span>
                    </a>
                  </div>
                  <div class="col-md-2">
                    <div class="rating-buttons">
                      <button id="upvote-button" class="submit btn btn-default" data-action="upvoted">
                        <i class="fa fa-thumbs-o-up" aria-hidden="true"></i>
                      </button>
                      <button id="downvote-button" class="submit btn btn-default" data-action="downvoted">
                        <i class="fa fa-thumbs-o-down" aria-hidden="true"></i>
                      </button>
                    </div>
                  </div>
                </div>
              </h4>
            </div>
            <div id="notification-data-{{ forloop.counter }}" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="notification-heading-{{ forloop.counter }}">
              <div class="panel-body">
                  {{ notification.summary|safe }}
              </div>
            </div>
          </div> <!-- <div class="panel panel-default -->
        {% endfor %}
      </div>
    </div>
    <div class="col-md-3 notification-date-list">
      <div id="date-list" class="list-group">
      </div>
    </div>
  </div>

  {% if filter_form %}
    {{ filter_form }}
  {% endif %}

{% endblock content %}

{% block javascript %}
{{ block.super }}
  <script>$('#accordion .collapse').collapse('hide');</script>
  <script type="text/javascript" src="{% static 'js/notification-date-list.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/notification-list-rating.js' %}"></script>
{% endblock %}

instanotifier/templates/api/notification/rssnotification_date_list.html
{% extends "base.html" %}

{% block content %}
<div class="list-group">
  {% for object in results %}
  <a class="list-group-item" data-id="" href="{% url 'api-v1:rssnotification-list' %}?published_parsed__date={{ object.published_parsed_date }}">
    {{ object.published_parsed_date }} - {{ object.dates_count }}
  </a>
  {% endfor %}
</div>

{% endblock %}